create table public.properties (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  description text null,
  original_price double precision null,
  price double precision null,
  currency character varying null,
  property_type character varying null,
  transaction_type character varying null,
  area real null,
  full_area real null,
  rooms smallint null,
  baths smallint null,
  location json null,
  address character varying null,
  created_by character varying not null,
  constraint properties_pkey primary key (id)
) TABLESPACE pg_default;


create table public.images (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  url text not null,
  name character varying null,
  property_id bigint not null,
  constraint images_pkey primary key (id),
  constraint images_property_id_fkey foreign KEY (property_id) references properties (id)
) TABLESPACE pg_default;